# Vale on the Markdown files, run by `make vale`. The three rules, each an error, are vendored
# with their licenses. They come from errata-ai's packages Microsoft 0.15.1, write-good 0.4.1 and
# proselint 0.3.4.
StylesPath = .vale/styles
MinAlertLevel = suggestion

[*.md]
Microsoft.SentenceLength = error
write-good.TooWordy = error
proselint.Needless = error
