---
galaxy_info:
  author: zadykian
  description: Packages, locale, timezone and unattended-upgrades
  license: MIT
  min_ansible_version: "2.20"
  platforms:
    - name: Ubuntu
      versions: [resolute]
dependencies: []
